import "./with-resolvers.js";

import { $ } from "./helpers.cpp";
import { readStrC16 } from "./shared.js";
import { bar2, foo } from "./test.cpp";
import "./test2.cpp";
(async () => {
    await $.untilInstantiated();
    let ptr = bar2();
    
    
    let str = readStrC16($.memory.buffer, ptr);

    console.log(str);

    foo();
})()

/*
import "./core/src/BarcodeFormat.cpp";
import "./core/src/BinaryBitmap.cpp";
import "./core/src/BitArray.cpp";
import "./core/src/BitMatrix.cpp";
import "./core/src/BitMatrixIO.cpp";
import "./core/src/BitSource.cpp";
import "./core/src/CharacterSet.cpp";
import "./core/src/ConcentricFinder.cpp";
import "./core/src/Content.cpp";
import "./core/src/DecodeHints.cpp";
import "./core/src/ECI.cpp";
import "./core/src/GTIN.cpp";
import "./core/src/GenericGF.cpp";
import "./core/src/GenericGFPoly.cpp";
import "./core/src/GlobalHistogramBinarizer.cpp";
import "./core/src/GridSampler.cpp";
import "./core/src/HRI.cpp";
import "./core/src/HybridBinarizer.cpp";
import "./core/src/MultiFormatReader.cpp";
import "./core/src/MultiFormatWriter.cpp";
import "./core/src/PerspectiveTransform.cpp";
import "./core/src/ReadBarcode.cpp";
import "./core/src/ReedSolomonDecoder.cpp";
import "./core/src/ReedSolomonEncoder.cpp";
import "./core/src/Result.cpp";
import "./core/src/ResultPoint.cpp";
import "./core/src/TextDecoder.cpp";
import "./core/src/TextEncoder.cpp";
import "./core/src/TextUtfEncoding.cpp";
import "./core/src/Utf.cpp";
import "./core/src/WhiteRectDetector.cpp";
import "./core/src/ZXBigInteger.cpp";
import "./core/src/aztec/AZDecoder.cpp";
import "./core/src/aztec/AZDetector.cpp";
import "./core/src/aztec/AZEncoder.cpp";
import "./core/src/aztec/AZHighLevelEncoder.cpp";
import "./core/src/aztec/AZReader.cpp";
import "./core/src/aztec/AZToken.cpp";
import "./core/src/aztec/AZWriter.cpp";
import "./core/src/datamatrix/DMBitLayout.cpp";
import "./core/src/datamatrix/DMDataBlock.cpp";
import "./core/src/datamatrix/DMDecoder.cpp";
import "./core/src/datamatrix/DMDetector.cpp";
import "./core/src/datamatrix/DMECEncoder.cpp";
import "./core/src/datamatrix/DMHighLevelEncoder.cpp";
import "./core/src/datamatrix/DMReader.cpp";
import "./core/src/datamatrix/DMSymbolInfo.cpp";
import "./core/src/datamatrix/DMVersion.cpp";
import "./core/src/datamatrix/DMWriter.cpp";
import "./core/src/libzueci/zueci.c";
import "./core/src/maxicode/MCBitMatrixParser.cpp";
import "./core/src/maxicode/MCDecoder.cpp";
import "./core/src/maxicode/MCReader.cpp";
import "./core/src/oned/ODCodabarReader.cpp";
import "./core/src/oned/ODCodabarWriter.cpp";
import "./core/src/oned/ODCode128Patterns.cpp";
import "./core/src/oned/ODCode128Reader.cpp";
import "./core/src/oned/ODCode128Writer.cpp";
import "./core/src/oned/ODCode39Reader.cpp";
import "./core/src/oned/ODCode39Writer.cpp";
import "./core/src/oned/ODCode93Reader.cpp";
import "./core/src/oned/ODCode93Writer.cpp";
import "./core/src/oned/ODDataBarCommon.cpp";
import "./core/src/oned/ODDataBarExpandedBitDecoder.cpp";
import "./core/src/oned/ODDataBarExpandedReader.cpp";
import "./core/src/oned/ODDataBarReader.cpp";
import "./core/src/oned/ODEAN13Writer.cpp";
import "./core/src/oned/ODEAN8Writer.cpp";
import "./core/src/oned/ODITFReader.cpp";
import "./core/src/oned/ODITFWriter.cpp";
import "./core/src/oned/ODMultiUPCEANReader.cpp";
import "./core/src/oned/ODReader.cpp";
import "./core/src/oned/ODRowReader.cpp";
import "./core/src/oned/ODUPCAWriter.cpp";
import "./core/src/oned/ODUPCEANCommon.cpp";
import "./core/src/oned/ODUPCEWriter.cpp";
import "./core/src/oned/ODWriterHelper.cpp";
import "./core/src/pdf417/PDFBarcodeValue.cpp";
import "./core/src/pdf417/PDFBoundingBox.cpp";
import "./core/src/pdf417/PDFCodewordDecoder.cpp";
import "./core/src/pdf417/PDFDecoder.cpp";
import "./core/src/pdf417/PDFDetectionResult.cpp";
import "./core/src/pdf417/PDFDetectionResultColumn.cpp";
import "./core/src/pdf417/PDFDetector.cpp";
import "./core/src/pdf417/PDFEncoder.cpp";
import "./core/src/pdf417/PDFHighLevelEncoder.cpp";
import "./core/src/pdf417/PDFModulusGF.cpp";
import "./core/src/pdf417/PDFModulusPoly.cpp";
import "./core/src/pdf417/PDFReader.cpp";
import "./core/src/pdf417/PDFScanningDecoder.cpp";
import "./core/src/pdf417/PDFWriter.cpp";
import "./core/src/qrcode/QRBitMatrixParser.cpp";
import "./core/src/qrcode/QRCodecMode.cpp";
import "./core/src/qrcode/QRDataBlock.cpp";
import "./core/src/qrcode/QRDecoder.cpp";
import "./core/src/qrcode/QRDetector.cpp";
import "./core/src/qrcode/QREncoder.cpp";
import "./core/src/qrcode/QRErrorCorrectionLevel.cpp";
import "./core/src/qrcode/QRFormatInformation.cpp";
import "./core/src/qrcode/QRMaskUtil.cpp";
import "./core/src/qrcode/QRMatrixUtil.cpp";
import "./core/src/qrcode/QRReader.cpp";
import "./core/src/qrcode/QRVersion.cpp";
import "./core/src/qrcode/QRWriter.cpp";
*/